### PR TITLE
[14.0][ADD] followers_mass_invoice_mailing: include followers in the mass mailing of invoices.

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
…mass mailing of invoices.

### CODE REVIEW

**Review by HaraldPanten — CHANGES_REQUESTED** [review]
@angelgarciadelachica Could you amend the commit message?

Remember that a new module needs to have the [ADD] tag, instead of [NEW].

THX.

**Comment by HaraldPanten** [comment]
@ValentinVinagre I'm still waiting for the commit amend.

**Comment by angelgarciadelachica** [comment]
@HaraldPanten Right, sorry. It's already changed!

**Review by HaraldPanten — APPROVED** [review]
THX @angelgarciadelachica LGTM

@ValentinVinagre I think we could merge this one.

👍

**Review by ValentinVinagre — APPROVED** [review]

**Pull request merged**
